{
  "id": "CVE-2020-4618",
  "assigner": "psirt@us.ibm.com",
  "Published": "2020-09-22T12:15:12.923Z",
  "Modified": "2020-09-22T15:08:59.12Z",
  "last-modified": "2020-09-22T15:08:59.12Z",
  "summary": "IBM Data Risk Manager (iDNA) 2.0.6 could allow a privileged user to cause a denial of service due to improper input validation. IBM X-Force ID: 184937.",
  "access": {
    "authentication": "SINGLE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 4.0,
  "exploitabilityScore": 8.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
  "references": [
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/184937",
    "https://www.ibm.com/support/pages/node/6335281"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "ibm"
  ],
  "products": [
    "data_risk_manager"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:ibm:data_risk_manager"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:ibm:data_risk_manager"
  ],
  "cwe": "CWE-20",
  "vulnerable_configuration_cpe_2_2": []
}