{
  "id": "CVE-2011-4944",
  "assigner": "secalert@redhat.com",
  "Published": "2012-08-27T21:55:01.29Z",
  "Modified": "2019-10-25T09:53:59.117Z",
  "last-modified": "2019-10-25T09:53:59.117Z",
  "summary": "Python 2.6 through 3.2 creates ~/.pypirc with world-readable permissions before changing them after data has been written, which introduces a race condition that allows local users to obtain a username and password by reading this file.",
  "access": {
    "authentication": "NONE",
    "complexity": "MEDIUM",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "NONE",
    "confidentiality": "PARTIAL",
    "integrity": "NONE"
  },
  "cvss": 1.9,
  "exploitabilityScore": 3.4,
  "impactScore": 2.9,
  "cvss-vector": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
  "references": [
    "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=650555",
    "http://bugs.python.org/file23824/pypirc-secure.diff",
    "http://bugs.python.org/issue13512",
    "http://lists.apple.com/archives/security-announce/2013/Oct/msg00004.html",
    "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html",
    "http://www.openwall.com/lists/oss-security/2012/03/27/10",
    "http://www.openwall.com/lists/oss-security/2012/03/27/2",
    "http://www.openwall.com/lists/oss-security/2012/03/27/5",
    "http://www.ubuntu.com/usn/USN-1592-1",
    "http://www.ubuntu.com/usn/USN-1596-1",
    "http://www.ubuntu.com/usn/USN-1613-1",
    "http://www.ubuntu.com/usn/USN-1613-2",
    "http://www.ubuntu.com/usn/USN-1615-1",
    "http://www.ubuntu.com/usn/USN-1616-1",
    "https://bugzilla.redhat.com/show_bug.cgi?id=758905"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-264",
  "vulnerable_configuration_cpe_2_2": []
}