{
  "id": "CVE-2019-19588",
  "assigner": "cve@mitre.org",
  "Published": "2019-12-05T00:15:14.317Z",
  "Modified": "2020-08-24T15:37:01.14Z",
  "last-modified": "2020-08-24T15:37:01.14Z",
  "summary": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "COMPLETE",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 7.8,
  "exploitabilityScore": 10.0,
  "impactScore": 6.9,
  "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:C",
  "references": [
    "https://github.com/kvesteri/validators/issues/86"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:validators_project:validators:0.12.2:*:*:*:*:python:*:*",
    "cpe:2.3:a:validators_project:validators:0.12.3:*:*:*:*:python:*:*",
    "cpe:2.3:a:validators_project:validators:0.12.4:*:*:*:*:python:*:*",
    "cpe:2.3:a:validators_project:validators:0.12.5:*:*:*:*:python:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:validators_project:validators:0.12.2:*:*:*:*:python:*:*",
    "cpe:2.3:a:validators_project:validators:0.12.3:*:*:*:*:python:*:*",
    "cpe:2.3:a:validators_project:validators:0.12.4:*:*:*:*:python:*:*",
    "cpe:2.3:a:validators_project:validators:0.12.5:*:*:*:*:python:*:*"
  ],
  "vendors": [
    "validators_project"
  ],
  "products": [
    "validators"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:validators_project:validators"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:validators_project:validators"
  ],
  "cwe": "CWE-835",
  "vulnerable_configuration_cpe_2_2": []
}