{
  "id": "CVE-2022-21133",
  "assigner": "secure@intel.com",
  "Published": "2022-02-09T22:15:17.783Z",
  "Modified": "2022-02-15T15:29:44.823Z",
  "last-modified": "2022-02-15T15:29:44.823Z",
  "summary": "Out-of-bounds read in the Intel(R) Trace Analyzer and Collector before version 2021.5 may allow an authenticated user to potentially enable denial of service via local access.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 2.1,
  "exploitabilityScore": 3.9,
  "impactScore": 2.9,
  "cvss-vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00639.html"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:intel:trace_analyzer_and_collector:2017:*:*:*:*:*:*:*",
    "cpe:2.3:a:intel:trace_analyzer_and_collector:2020:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:intel:trace_analyzer_and_collector:2017:*:*:*:*:*:*:*",
    "cpe:2.3:a:intel:trace_analyzer_and_collector:2020:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "intel"
  ],
  "products": [
    "trace_analyzer_and_collector"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:intel:trace_analyzer_and_collector"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:intel:trace_analyzer_and_collector"
  ],
  "cwe": "CWE-125",
  "vulnerable_configuration_cpe_2_2": []
}