{
  "id": "CVE-2013-4189",
  "assigner": "secalert@redhat.com",
  "Published": "2014-03-11T18:37:02.457Z",
  "Modified": "2014-03-12T00:02:41.19Z",
  "last-modified": "2014-03-12T00:02:41.19Z",
  "summary": "Multiple unspecified vulnerabilities in (1) dataitems.py, (2) get.py, and (3) traverseName.py in Plone 2.1 through 4.1, 4.2.x through 4.2.5, and 4.3.x through 4.3.1 allow remote authenticated users with administrator access to a subtree to access nodes above the subtree via unknown vectors.",
  "access": {
    "authentication": "SINGLE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 6.5,
  "exploitabilityScore": 8.0,
  "impactScore": 6.4,
  "cvss-vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P",
  "references": [
    "http://plone.org/products/plone-hotfix/releases/20130618",
    "http://plone.org/products/plone/security/advisories/20130618-announcement",
    "http://seclists.org/oss-sec/2013/q3/261",
    "https://bugzilla.redhat.com/show_bug.cgi?id=978450"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "NVD-CWE-noinfo",
  "vulnerable_configuration_cpe_2_2": []
}