{
  "id": "CVE-2014-1928",
  "assigner": "cve@mitre.org",
  "Published": "2014-10-25T19:55:03.85Z",
  "Modified": "2014-10-27T18:24:19.207Z",
  "last-modified": "2014-10-27T18:24:19.207Z",
  "summary": "The shell_quote function in python-gnupg 0.3.5 does not properly escape characters, which allows context-dependent attackers to execute arbitrary code via shell metacharacters in unspecified vectors, as demonstrated using \"\\\" (backslash) characters to form multi-command sequences, a different vulnerability than CVE-2014-1927.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2013-7323.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 4.6,
  "exploitabilityScore": 3.9,
  "impactScore": 6.4,
  "cvss-vector": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
  "references": [
    "http://seclists.org/oss-sec/2014/q1/246",
    "http://seclists.org/oss-sec/2014/q1/294",
    "http://www.debian.org/security/2014/dsa-2946",
    "https://code.google.com/p/python-gnupg/",
    "https://code.google.com/p/python-gnupg/issues/detail?id=98"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:python-gnupg_project:python-gnupg:0.3.5:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:python-gnupg_project:python-gnupg:0.3.5:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "python-gnupg_project"
  ],
  "products": [
    "python-gnupg"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:python-gnupg_project:python-gnupg"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:python-gnupg_project:python-gnupg"
  ],
  "cwe": "CWE-20",
  "vulnerable_configuration_cpe_2_2": []
}