{
  "id": "CVE-2022-2996",
  "assigner": "secalert@redhat.com",
  "Published": "2022-09-01T16:15:09.147Z",
  "Modified": "2022-12-12T20:09:43.077Z",
  "last-modified": "2022-12-12T20:09:43.077Z",
  "summary": "A flaw was found in the python-scciclient when making an HTTPS connection to a server where the server's certificate would not be verified. This issue opens up the connection to possible Man-in-the-middle (MITM) attacks.",
  "access": {
    "authentication": null,
    "complexity": null,
    "vector": null
  },
  "impact": {
    "availability": null,
    "confidentiality": null,
    "integrity": null
  },
  "cvss": null,
  "exploitabilityScore": null,
  "impactScore": null,
  "cvss-vector": null,
  "references": [
    "https://lists.debian.org/debian-lts-announce/2022/11/msg00006.html",
    "https://opendev.org/x/python-scciclient/commit/274dca0344b65b4ac113d3271d21c17e970a636c"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-295",
  "vulnerable_configuration_cpe_2_2": []
}