{
  "id": "CVE-2017-6801",
  "assigner": "cve@mitre.org",
  "Published": "2017-03-10T09:59:00.547Z",
  "Modified": "2019-05-18T01:29:03.443Z",
  "last-modified": "2019-05-18T01:29:03.443Z",
  "summary": "An issue was discovered in ytnef before 1.9.2. There is a potential out-of-bounds access with fields of Size 0 in TNEFParse() in libytnef.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 5.0,
  "exploitabilityScore": 10.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "http://www.debian.org/security/2017/dsa-3846",
    "https://github.com/Yeraze/ytnef/commit/3cb0f914d6427073f262e1b2b5fd973e3043cdf7",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LFJWMUEUC4ILH2HEOCYVVLQT654ZMCGQ/"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:ytnef_project:ytnef:1.7:*:*:*:*:*:*:*",
    "cpe:2.3:a:ytnef_project:ytnef:1.8:*:*:*:*:*:*:*",
    "cpe:2.3:a:ytnef_project:ytnef:1.9:*:*:*:*:*:*:*",
    "cpe:2.3:a:ytnef_project:ytnef:1.9.1:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:ytnef_project:ytnef:1.7:*:*:*:*:*:*:*",
    "cpe:2.3:a:ytnef_project:ytnef:1.8:*:*:*:*:*:*:*",
    "cpe:2.3:a:ytnef_project:ytnef:1.9:*:*:*:*:*:*:*",
    "cpe:2.3:a:ytnef_project:ytnef:1.9.1:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "ytnef_project"
  ],
  "products": [
    "ytnef"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:ytnef_project:ytnef"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:ytnef_project:ytnef"
  ],
  "cwe": "CWE-125",
  "vulnerable_configuration_cpe_2_2": []
}