{
  "id": "CVE-2020-9306",
  "assigner": "cve@mitre.org",
  "Published": "2021-02-17T23:15:17.327Z",
  "Modified": "2021-07-21T09:39:23.747Z",
  "last-modified": "2021-07-21T09:39:23.747Z",
  "summary": "Tesla SolarCity Solar Monitoring Gateway through 5.46.43 has a \"Use of Hard-coded Credentials\" issue because Digi ConnectPort X2e uses a .pyc file to store the cleartext password for the python user account.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "ADJACENT_NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 5.8,
  "exploitabilityScore": 6.5,
  "impactScore": 6.4,
  "cvss-vector": "AV:A/AC:L/Au:N/C:P/I:P/A:P",
  "references": [
    "https://github.com/fireeye/Vulnerability-Disclosures/blob/master/FEYE-2020-0019/FEYE-2020-0019.md",
    "https://www.fireeye.com/blog/threat-research.html",
    "https://www.fireeye.com/blog/threat-research/2021/02/solarcity-exploitation-of-x2e-iot-device-part-one.html",
    "https://www.fireeye.com/blog/threat-research/2021/02/solarcity-exploitation-of-x2e-iot-device-part-two.html"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:tesla:solarcity_solar_monitoring_gateway:-:*:*:*:*:*:*:*",
    "cpe:2.3:a:tesla:solarcity_solar_monitoring_gateway:5.46.43:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:tesla:solarcity_solar_monitoring_gateway:-:*:*:*:*:*:*:*",
    "cpe:2.3:a:tesla:solarcity_solar_monitoring_gateway:5.46.43:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "tesla"
  ],
  "products": [
    "solarcity_solar_monitoring_gateway"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:tesla:solarcity_solar_monitoring_gateway"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:tesla:solarcity_solar_monitoring_gateway"
  ],
  "cwe": "CWE-798",
  "vulnerable_configuration_cpe_2_2": []
}