{
  "id": "CVE-2017-7233",
  "assigner": "cve@mitre.org",
  "Published": "2017-04-04T15:59:00.273Z",
  "Modified": "2018-10-17T08:29:15.073Z",
  "last-modified": "2018-10-17T08:29:15.073Z",
  "summary": "Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely ``django.utils.http.is_safe_url()``) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.",
  "access": {
    "authentication": "NONE",
    "complexity": "MEDIUM",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "NONE",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 5.8,
  "exploitabilityScore": 8.6,
  "impactScore": 4.9,
  "cvss-vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N",
  "references": [
    "http://www.debian.org/security/2017/dsa-3835",
    "http://www.securityfocus.com/bid/97406",
    "http://www.securitytracker.com/id/1038177",
    "https://access.redhat.com/errata/RHSA-2017:1445",
    "https://access.redhat.com/errata/RHSA-2017:1451",
    "https://access.redhat.com/errata/RHSA-2017:1462",
    "https://access.redhat.com/errata/RHSA-2017:1470",
    "https://access.redhat.com/errata/RHSA-2017:1596",
    "https://access.redhat.com/errata/RHSA-2017:3093",
    "https://access.redhat.com/errata/RHSA-2018:2927",
    "https://www.djangoproject.com/weblog/2017/apr/04/security-releases/"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-601",
  "vulnerable_configuration_cpe_2_2": []
}